Components/CartSummaryViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BookStoreProject.Models;

// Component that allows the shopping cart icon to work 

namespace BookStoreProject.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }

    }
}

Components/NavigationMenuViewComponent.cs
using BookStoreProject.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStoreProject.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {

        private IBookRepository repository;
        public NavigationMenuViewComponent (IBookRepository r)
        {
            repository = r;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];

            return View(repository.Projects
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x));
        }
    }
}

Views/Shared/BookSummary.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Project

<tr class="">
    <td>@Model.Title</td>
    <td>@Model.Author</td>
    <td>@Model.Publisher</td>
    <td>@Model.ISBN</td>
    <td>@Model.Classification</td>
    <td>@Model.Category</td>
    <td>@Model.Price</td>
    <td>@Model.BookPages</td>
    <td>
        <form id="@Model.BookID" asp-page="/Purchase" method="post">
            <input type="hidden" asp-for="BookID" />
            <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
            <span class="card-text p-1">
                <!--Model.Title-->
                <button type="submit" class="btn-success btn-sm pull-right" style="float:right">
                    Add
                </button>

            </span>
        </form>
    </td>
    
</tr>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStoreProject</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>

    <!-- Navbar -->

    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">BOOK STORE</div>
                <div class="col-6 text-right">
                    <vc:cart-summary />
                </div>
            </div>
        </div>
    </div>

    <br />
    <br />

    <div class="row">
        <vc:navigation-menu />

        <div>@RenderBody()</div>
    </div>

</body>
</html>