Pages/Purchase.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using BookStoreProject.Models;
using BookStoreProject.Infrastructure;

namespace BookStoreProject.Pages
{
    public class PurchaseModel : PageModel
    {
        private IBookRepository repository;

        // Constructor
        public PurchaseModel(IBookRepository repo, Cart cartService)
        {
            repository = repo;
            Cart = cartService;
        }

        // Properties
        public Cart Cart { get; set; }

        public string ReturnUrl { get; set; }

        // Methods
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }

        public IActionResult OnPost(long bookId, string returnUrl)
        {
            Project project = repository.Projects
                .FirstOrDefault(p => p.BookID == bookId);

            Cart.AddItem(project, 1);

            return RedirectToPage(new { returnUrl = returnUrl });
        }

        public IActionResult OnPostRemove(long bookId, string returnUrl)
        {
            Cart.RemoveLine(Cart.Lines.First(cl =>
                cl.Project.BookID == bookId).Project);
            return RedirectToPage(new { returnUrl = returnUrl });
        }
    }
}

Pages/Purchase.cshtml
@page
@model BookStoreProject.Pages.PurchaseModel
@{
}

<h2>Your Cart</h2>

<table class="table table-bordered table-striped">
    <tr>
        <th>Book</th><th>Quantity</th><th>Price</th><th>SubTotal</th><th> </th>
    </tr>
    <tbody>
        @foreach(var line in Model.Cart.Lines)
        {
        <tr>
            <td class="text-left">@line.Project.Title</td>
            <td class="text-center">@line.Quantity</td>
            <td class="text-right">@(line.Project.Price.ToString("c"))</td>
            <td class="text-right">@((line.Quantity * line.Project.Price).ToString("c"))</td>
            <td class="text-center">
                <form asp-page-handler="Remove" method="post">
                    <input type="hidden" name="BookID"
                           value="@line.Project.BookID" />
                    <input type="hidden" name="returnUrl"
                           value="@Model.ReturnUrl" />
                    <button type="submit" class="btn btn-sm btn-danger">
                        Remove
                    </button>
                </form>
            </td>

        </tr>
            
        }
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total:</td>
            <td class="text-right">@Model.Cart.ComputeTotalSum().ToString("c")</td>
        </tr>
    </tfoot>

    
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
</div>